feat(workflow): add Cloud Run revision tag cleanup
- Introduce `execute_cloudrun_revision_tag` input to workflows
- Add job to delete Cloud Run revision tags in `cleanup-common.yml`
- Update `cleanup.yml` to handle new input and prevent deletion in
production

diff --git a/.github/workflows/cleanup.yml b/.github/workflows/cleanup.yml
--- a/.github/workflows/cleanup.yml
+++ b/.github/workflows/cleanup.yml
@@ -14,6 +14,10 @@ on:
         description: "Delete all Github caches for the specified branch"
         type: boolean
         default: true
+      execute_cloudrun_revision_tag:
+        description: "Remove tags from Cloudrun revisions"
+        type: boolean
+        default: false
 
 jobs:
   get-config:
@@ -32,8 +36,15 @@ jobs:
         run: |
           if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
             if [ "${{ needs.get-config.outputs.ref_name_lowercase }}" == "main" ]; then 
+
               ## DockerImage in production environment cannot be deleted
               if [ "${{ github.event.inputs.artifact_repository }}" == "true" ]; then
+                echo "::error::Cannot cleanup to main branch directly via workflow_dispatch"
+                exit 1
+              fi
+
+              ## Revision Tag in production environment cannot be deleted
+              if [ "${{ github.event.inputs.execute_cloudrun_revision_tag }}" == "true" ]; then
                 echo "::error::Cannot cleanup to main branch directly via workflow_dispatch"
                 exit 1
               fi
@@ -59,6 +70,7 @@ jobs:
       repo_name: ${{ needs.get-config.outputs.repo_name_lowercase }}
       ref_name: ${{ needs.get-config.outputs.ref_name_lowercase }}
       execute_artifact_repository: ${{ github.event_name == 'pull_request' || github.event.inputs.artifact_repository == 'true' }}
+      execute_cloudrun_revision_tag: ${{ github.event_name == 'pull_request' || github.event.inputs.execute_cloudrun_revision_tag == 'true' }}
       execute_github_cache: ${{ github.event_name == 'pull_request' || github.event.inputs.github_cache == 'true' }}
     secrets: inherit
 
@@ -81,5 +93,6 @@ jobs:
       repo_name: ${{ needs.get-config.outputs.repo_name_lowercase }}
       ref_name: ${{ needs.get-config.outputs.ref_name_lowercase }}
       execute_artifact_repository: ${{ github.event_name == 'pull_request' || github.event.inputs.artifact_repository == 'true' }}
+      execute_cloudrun_revision_tag: ${{ github.event_name == 'pull_request' || github.event.inputs.execute_cloudrun_revision_tag == 'true' }}
       execute_github_cache: ${{ github.event_name == 'pull_request' || github.event.inputs.github_cache == 'true' }}
     secrets: inherit
